### ISSUE TITLE
v0.4 release tracking issue

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#122]
In v0.3 we will move some part out of this repo to improve CI time and precompile time. Also this will benefit other projects in the Julia ecosystem to re-use our utility. And on the other hand we will add some more features.

This issue will track what we will do next

### Make Yao a meta package

- [ ] create a base package
- [ ] separate block system
- [ ] separate registers
- [ ] integrate with CUDA

### We will drop v0.6 support

see #117 

### original `with` will be deleted

see #113 

### Hygine problem should be solved now

see #57 

### Derive some new packages from Yao

- [x] move `LuxurySparse` as a Julia package and add to deps
- [x] move `Yao.Zoo` to an extension package `QuAlgorithmZoo`, we will eventually implement (not in v0.3) some more algorithms described by [Quantum Algorithm Zoo](https://math.nist.gov/quantum/zoo/) in this package with utilities above.

### Derive new parts in Yao

- [ ] move some blocks out of `Yao.Blocks` to be an extension package of in a new module `Contrib.Extension`. This a standard extension including the following blocks:
   - [ ] `Roller`
   - *What else?*

The other extensions in `Contrib` should take this as an example.

### Deprecation fix

- [x] Block system
   - [x] Primitive Blocks
   - [x] Composite Blocks
   - [x] I/O
- [x] Registers
- [x] Interfaces

---

The following could be in separated package in the future (to be decided)

- [x] some part of the Block system
- [x] LuxurySparse
- [x] QuAlgorithmZoo

#### QASM support

Since [QASM](https://www.media.mit.edu/quanta/qasm2circ/) has been wildly supported by various projects, we will also support lowering our block tree structure to QASM. This will requires two feature

- [ ] dumping to QASM from block tree
- [ ] ~~parse QASM strings to block tree (this may not be supported in v0.3, I guess)~~

#### Time evolution support

See #41  This is currently developing by @GiggleLiu , we will discuss whether this goes in`YaoStdExt` with other part of the Block system or not.

#### Tensor network based acceleration (could be in v0.3)

Tensor network algorithms can be used to accelerate certain kind of circuit.

#### Parallized batched registers

See #13. This was an early request of parallelism, which is quite useful when you need to run the circuit for multiple times.

Any suggestions?
