### ISSUE TITLE
Make Yao a meta package 

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#159]
This is a proposal which will make Yao.jl a meta package of several concrete package for quantum information science like `DifferentialEquations`.

By separating each different part into several packages, it will be easier to maintain mature part of the package, and develop new features in separated repo rapidly.  

## Name conventions

All the package will start with `Yao` to enable tab completion for convenience.

## Mature part of the package

- [x] `YaoBase`, this package includes the abstract register, testing tools, and miscellanea
- [x] `YaoArrayRegister`, this package includes the default dense register implementation
- [ ] `YaoBlockTree`, this package provides the block tree abstraction

## Packages will be under early stage

- [ ] `CuYao`, this package includes the CUDA register and block operations.
- [ ] `YaoAD/YaoFlux`, this package includes the automatic differentiation for quantum circuits

## Package separated for general use

- [x] `BitBasis` 

In the future, `Yao.jl` will only provide a few eye-candy and ester egg and re-export the above package as a meta-package.

**Comment by GiggleLiu** [comment]
Please don't change the name of `CuYao`, this name has been widely used in my slides and my recent paper. Not all packages in GPUJulia start with `GPU`, right?
So, please remove `tab completion for convenience`, this is not a reason.

**Comment by Roger-luo** [comment]
`CuYao` will become a meta package as well to make it easier to install, since we don't have conditional dependency in Pkg. (Ref: https://github.com/JuliaLang/Pkg.jl/pull/977)

`CuYao` will contain the following:

- what's in Yao.jl for CPU and reexport what's Yao has
- CUDA kernels (this might be move out of the repo to `YaoCuArrayRegister` later), but we keep it in `CuYao` for now.
