### ISSUE TITLE
release v0.7 tracking

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#272]
I think we should have a release v0.7 which provides some basic upgrades of each component of Yao, a few items should be included:

- [ ] new simulator backend
- [ ] IBMQ client for blocks
- [ ] put a deprecation warning for Yao script in this version

I think we will need a version to include the compiler before v1.0, perhaps v0.8 given the current status of development.
